// AUTO-GENERATED by the mil-catalog Haiku workflow — do not edit by hand.
// Re-run the workflow to regenerate. Figures are public open-source estimates.
import type { CatalogItem } from './catalog.js';

export const GENERATED_CATALOG: CatalogItem[] = [
  {
    "id": "harop",
    "name": "IAI Harop",
    "category": "loitering_munition",
    "country": "Israel",
    "role": "Anti-radiation loitering munition; searches and destroys radar emitters",
    "specs": {
      "range_km": 250,
      "speed_kph": 200,
      "ceiling_m": 5000,
      "payload_kg": 32,
      "pk_est": 0.65,
      "cost_usd": 2000000
    },
    "sources": [
      "Wikipedia IAI Harop article",
      "CSIS Missile Threat Database",
      "IAI Israel Aerospace Industries manufacturer specifications"
    ],
    "notes": "Loitering munition designed for autonomous RF-homing to radar emitters with 6+ hour endurance. Uses electro-optical/infrared sensors and operator manual-override capability. Operat"
  },
  {
    "id": "shahed-136",
    "name": "Shahed-136 / Geran-2",
    "category": "loitering_munition",
    "country": "Iran / Russia",
    "role": "One-way attack drone; point-to-point cruise-missile profile",
    "specs": {
      "range_km": 2500,
      "speed_kph": 185,
      "ceiling_m": 3500,
      "payload_kg": 50,
      "pk_est": 0.35,
      "cost_usd": 56500
    },
    "sources": [
      "Wikipedia:Shahed-136",
      "Wikipedia:Geran-2",
      "Jane's Intelligence Review (17 May 2023)"
    ],
    "notes": "Shahed-136 is an Iranian-origin one-way attack drone (loitering munition classification disputed by RUSI due to limited loitering behavior; primarily used point-to-point). Operates"
  },
  {
    "id": "switchblade-300",
    "name": "Switchblade 300",
    "category": "loitering_munition",
    "country": "USA",
    "role": "Precision loitering strike munition for BLOS antipersonnel and light vehicle targets",
    "specs": {
      "range_km": 10,
      "speed_kph": 160,
      "ceiling_m": 4600,
      "payload_kg": 1.8,
      "pk_est": 0.75,
      "cost_usd": 6000
    },
    "sources": [
      "Wikipedia: AeroVironment Switchblade",
      "AeroVironment official: Switchblade 300 Block 20",
      "Army Recognition: Switchblade 300 Loitering Munition"
    ],
    "notes": "Miniature backpackable loitering munition developed by AeroVironment. Carries 1.8 kg warhead (40mm grenade equivalent). Block 20 variant offers extended endurance to ~20 minutes vs"
  },
  {
    "id": "switchblade-600",
    "name": "Switchblade 600",
    "category": "loitering_munition",
    "country": "United States",
    "role": "Man-portable anti-armor loitering munition with 80 km range and 40+ min endurance",
    "specs": {
      "range_km": 80,
      "speed_kph": 185,
      "ceiling_m": 4600,
      "payload_kg": 9,
      "pk_est": 0.75,
      "cost_usd": 75000
    },
    "sources": [
      "AeroVironment official product page (avinc.com)",
      "Army Recognition military database",
      "EDR Magazine"
    ],
    "notes": "Tandem HEAT warhead (based on FGM-148 Javelin) capable of 600–800 mm armor penetration behind ERA. Block 2 variant offers extended 50+ min endurance. System weight 54.5 kg total (a"
  },
  {
    "id": "warmate",
    "name": "WB Group Warmate",
    "category": "loitering_munition",
    "country": "Poland",
    "role": "Precision strike loitering munition for tactical and anti-armor targets",
    "specs": {
      "range_km": 100,
      "speed_kph": 150,
      "ceiling_m": 3500,
      "payload_kg": 8,
      "pk_est": 0.75,
      "cost_usd": 50000
    },
    "sources": [
      "Wikipedia: WB Electronics Warmate",
      "Army Recognition: Poland Launches Warmate 5.0",
      "Jane's Defence Intelligence"
    ],
    "notes": "Warmate family includes original variant (5.7kg, 30km range, 300g HE warhead), Warmate 2 (30kg, 30-240km range), Warmate 3 (3kg warhead, 80+ km range, 90 km/h cruise, 3500m ceiling"
  },
  {
    "id": "lancet-3",
    "name": "ZALA Lancet-3",
    "category": "loitering_munition",
    "country": "Russia",
    "role": "Loitering munition for precision strike on armor and static targets",
    "specs": {
      "range_km": 40,
      "speed_kph": 110,
      "ceiling_m": 5000,
      "payload_kg": 3,
      "pk_est": 0.78,
      "cost_usd": 30000
    },
    "sources": [
      "Wikipedia: ZALA Lancet",
      "Army Recognition: Lancet-3 fact sheet",
      "Grey Dynamics: Lancet-3 Russia's Spear in the Sky"
    ],
    "notes": "Cruise speed 80-110 km/h with dive acceleration to 300+ km/h. Electric motor, dual X-shaped wing configuration. Payload: HE, HE-fragmentation, or shaped charge warheads (3-5 kg var"
  },
  {
    "id": "bayraktar-tb2",
    "name": "Bayraktar TB2",
    "category": "drone",
    "country": "Turkey",
    "role": "Medium-altitude long-endurance tactical strike UAV",
    "specs": {
      "range_km": 300,
      "speed_kph": 222,
      "ceiling_m": 8230,
      "payload_kg": 150,
      "pk_est": 0.75,
      "cost_usd": 5000000
    },
    "sources": [
      "Wikipedia - Bayraktar TB2",
      "Global Military & Defense (2026)",
      "Army Recognition"
    ],
    "notes": "Bayraktar TB2 is a domestically-developed Turkish MALE UCAV armed with indigenous MAM-L (~22 kg) and MAM-C (~6.5 kg) guided munitions. Holds Turkish aviation records for endurance "
  },
  {
    "id": "scaneagle",
    "name": "Boeing Insitu ScanEagle",
    "category": "drone",
    "country": "United States",
    "role": "Long-endurance tactical ISR",
    "specs": {
      "range_km": 100,
      "speed_kph": 148,
      "ceiling_m": 5950,
      "payload_kg": 8,
      "cost_usd": 1400000
    },
    "sources": [
      "Wikipedia: Boeing Insitu MQ-27 ScanEagle",
      "Insitu official product page",
      "GlobalMilitary.net"
    ]
  },
  {
    "id": "heron-tp",
    "name": "IAI Heron TP",
    "category": "drone",
    "country": "Israel",
    "role": "Medium-altitude long-endurance ISR/reconnaissance",
    "specs": {
      "range_km": 250,
      "speed_kph": 150,
      "ceiling_m": 7600,
      "payload_kg": 250,
      "pk_est": 0.72,
      "cost_usd": 20000000
    },
    "sources": [
      "Wikipedia IAI Heron",
      "IAI official specifications",
      "CSIS Missile Threat database"
    ],
    "notes": "Tactical Patrol variant emphasizes 40+ hour endurance and modular payload bay (EO/IR, SAR, SIGINT). MTOW 1,250 kg. Primary mission is reconnaissance/target acquisition. Cost estima"
  },
  {
    "id": "mq9-reaper",
    "name": "MQ-9 Reaper",
    "category": "drone",
    "country": "United States",
    "role": "Armed surveillance and hunter-killer UAV",
    "specs": {
      "range_km": 1850,
      "speed_kph": 280,
      "ceiling_m": 7600,
      "payload_kg": 1700,
      "pk_est": 0.72,
      "cost_usd": 34000000
    },
    "sources": [
      "Wikipedia: General Atomics MQ-9 Reaper",
      "CSIS Defense360 — MQ-9 Reaper",
      "U.S. Air Force Fact Sheet"
    ],
    "notes": "MQ-9A baseline variant (original combat model): 66 ft wingspan, 36 ft length, Honeywell TPE331 900 hp turboprop. Operational ceiling 25,000 ft (7,600 m); max speed 260 kts (~480 kp"
  },
  {
    "id": "orlan-10",
    "name": "Orlan-10",
    "category": "drone",
    "country": "Russia",
    "role": "Tactical reconnaissance UAV",
    "specs": {
      "range_km": 40,
      "speed_kph": 40,
      "ceiling_m": 1500,
      "payload_kg": 3.5,
      "pk_est": 0.4,
      "cost_usd": 25000
    },
    "sources": [
      "Wikipedia (Orlan-10)",
      "Russian manufacturer Zala Aero/Pella",
      "CSIS Missile Threat database"
    ],
    "notes": "Tactical-level reconnaissance UAV extensively used by Russian forces from 2014+. Catapult-launched with parachute recovery. Primary role: forward observation, target acquisition, B"
  },
  {
    "id": "wing-loong-2",
    "name": "Wing Loong II",
    "category": "drone",
    "country": "China",
    "role": "Medium-altitude long-endurance armed reconnaissance UAV",
    "specs": {
      "range_km": 2000,
      "speed_kph": 200,
      "ceiling_m": 9900,
      "payload_kg": 400,
      "pk_est": 0.8
    },
    "sources": [
      "https://en.wikipedia.org/wiki/CAIG_Wing_Loong_II",
      "https://www.janes.com/osint-insights/defence-news/air/wing-loong-ii-uav-being-developed-for-diverse-roles",
      "https://www.defensenews.com/smr/unmanned-unleashed/2017/03/01/latest-generation-chinese-combat-drone-makes-maiden-flight/"
    ]
  },
  {
    "id": "avenger",
    "name": "AN/TWQ-1 Avenger",
    "category": "sam",
    "country": "United States",
    "role": "Short-range mobile air defense (SHORAD)",
    "specs": {
      "range_km": 8,
      "speed_kph": 2100,
      "ceiling_m": 3800,
      "payload_kg": 2.25,
      "pk_est": 0.65,
      "cost_usd": 40000000
    },
    "sources": [
      "Wikipedia: AN/TWQ-1 Avenger",
      "Raytheon/RTX manufacturer documentation",
      "U.S. Department of Defense budget justifications"
    ],
    "notes": "Mobile air defense system mounted on Humvee chassis with quad-pack Stinger missile launcher and Phalanx radar. Specifications reflect Stinger missile performance. Primary short-ran"
  },
  {
    "id": "buk-m3",
    "name": "Buk-M3",
    "category": "sam",
    "country": "Russia",
    "role": "Medium-range self-propelled air defense system",
    "specs": {
      "range_km": 70,
      "speed_kph": 4300,
      "ceiling_m": 35000,
      "pk_est": 0.75,
      "cost_usd": 350000000
    },
    "sources": [
      "Wikipedia: Buk missile system",
      "CSIS Missile Threat database",
      "IISS Military Balance"
    ],
    "notes": "Buk-M3 is the latest operational variant (deployed 2015-2017+) with upgraded AESA-type radar, improved command post, and enhanced low-altitude coverage. Range cited is maximum agai"
  },
  {
    "id": "stinger",
    "name": "FIM-92 Stinger (MANPADS)",
    "category": "sam",
    "country": "United States",
    "role": "Infrared-guided man-portable air defense system",
    "specs": {
      "range_km": 4.8,
      "speed_kph": 2725,
      "ceiling_m": 3800,
      "payload_kg": 3,
      "pk_est": 0.65,
      "cost_usd": 119000
    },
    "sources": [
      "Wikipedia - FIM-92 Stinger",
      "GlobalSecurity.org - FIM-92A Stinger Weapons System",
      "Army Technology - Stinger MANPADS"
    ],
    "notes": "Fire-and-forget infrared homing SAM developed by General Dynamics (now Raytheon), entered US service 1981. System weight ~16 kg including launcher. Effective against aircraft, heli"
  },
  {
    "id": "iris-t-slm",
    "name": "IRIS-T SLM",
    "category": "sam",
    "country": "Germany",
    "role": "Medium-range surface-to-air missile system",
    "specs": {
      "range_km": 40,
      "speed_kph": 3672,
      "ceiling_m": 20000,
      "payload_kg": 11.4,
      "pk_est": 0.95,
      "cost_usd": 430000
    },
    "sources": [
      "Wikipedia: IRIS-T SL",
      "Army Recognition: IRIS-T SLM technical data",
      "Norsk luftvern: IRIS-T SL Air Defense System Cost Analysis"
    ],
    "notes": "IRIS-T SLM is a medium-range air defense system developed by German company Diehl Defence. The system provides 360° coverage against aircraft, helicopters, cruise missiles, and gui"
  },
  {
    "id": "iron-dome",
    "name": "Iron Dome",
    "category": "sam",
    "country": "Israel",
    "role": "Short-range air defense against rockets and missiles",
    "specs": {
      "range_km": 70,
      "speed_kph": 0,
      "ceiling_m": 10000,
      "payload_kg": 0,
      "pk_est": 0.9,
      "cost_usd": 50000
    },
    "sources": [
      "Wikipedia: Iron Dome",
      "CSIS Missile Threat: Iron Dome (Israel)",
      "Rafael Advanced Defense Systems: Iron Dome system documentation"
    ],
    "notes": "Tamir interceptor: 3 m long, 0.16 m diameter, 90 kg launch weight (total missile mass). Uses high-explosive blast-fragmentation warhead. Each battery defends ~150 km². System equip"
  },
  {
    "id": "patriot-pac3",
    "name": "MIM-104 Patriot PAC-3",
    "category": "sam",
    "country": "United States",
    "role": "All-altitude air defense and cruise missile intercept",
    "specs": {
      "range_km": 100,
      "speed_kph": 4700,
      "ceiling_m": 27000,
      "payload_kg": 9,
      "pk_est": 0.88,
      "cost_usd": 4000000
    },
    "sources": [
      "Wikipedia - MIM-104 Patriot",
      "Raytheon Missiles & Fire Control - Patriot PAC-3 Brochure",
      "U.S. Department of Defense Fact Sheet - Patriot System"
    ],
    "notes": "PAC-3 variant (Patriot Advanced Capability-3) entered service 1999. Uses hit-to-kill kinetic warhead (~9 kg) optimized for cruise missiles and aircraft. Range varies 40-160 km by t"
  },
  {
    "id": "nasams",
    "name": "NASAMS",
    "category": "sam",
    "country": "Norway / United States",
    "role": "Medium-range air defense system for aircraft and cruise missiles",
    "specs": {
      "range_km": 40,
      "speed_kph": 2200,
      "ceiling_m": 21000,
      "payload_kg": 18,
      "pk_est": 0.78,
      "cost_usd": 145000000
    },
    "sources": [
      "Wikipedia NASAMS",
      "Kongsberg Defence & Aerospace official specs",
      "GlobalSecurity.org NASAMS"
    ],
    "notes": "NASAMS 2 fires standard AMRAAM with 40 km range and 21 km ceiling; NASAMS 3 uses AMRAAM-ER extending range to 60 km and ceiling to 35.7 km. Primary missile is Raytheon's air-to-air"
  },
  {
    "id": "pantsir-s1",
    "name": "Pantsir-S1",
    "category": "sam",
    "country": "Russia",
    "role": "Close-range air defense vs aircraft, helicopters, drones, cruise missiles",
    "specs": {
      "range_km": 20,
      "speed_kph": 6120,
      "ceiling_m": 10000,
      "pk_est": 0.65,
      "cost_usd": 15000000
    },
    "sources": [
      "CSIS Missile Threat (missilethreat.csis.org/defsys/pantsir-s-1/)",
      "Wikipedia Pantsir missile system (en.wikipedia.org/wiki/Pantsir_missile_system)",
      "Global Military database"
    ],
    "notes": "NATO designation SA-22 Greyhound. Self-propelled combined gun/missile SPAAGM system. Primary missile: 57E6 with 20 km max range vs tactical aircraft at 10 km altitude. Against subs"
  },
  {
    "id": "s-300",
    "name": "S-300",
    "category": "sam",
    "country": "Soviet Union / Russia",
    "role": "Long-range air defense system against aircraft, UAVs, and missiles",
    "specs": {
      "range_km": 90,
      "ceiling_m": 27000,
      "payload_kg": 143,
      "pk_est": 0.75
    },
    "sources": [
      "https://en.wikipedia.org/wiki/S-300_missile_system",
      "https://missilethreat.csis.org/defsys/s-300/"
    ],
    "notes": "Primary S-300PMU variant with 5V55R missile (75-90 km range). Warhead weight of 143 kg represents the latest version. Maximum engagement altitude 27,000m; minimum 25m. Pk estimate "
  },
  {
    "id": "s-400",
    "name": "S-400 Triumf",
    "category": "sam",
    "country": "Russia",
    "role": "Long-range air defense system with multi-target engagement capability",
    "specs": {
      "range_km": 400,
      "speed_kph": 10880,
      "ceiling_m": 30000,
      "payload_kg": 48,
      "pk_est": 0.85,
      "cost_usd": 750000000
    },
    "sources": [
      "Wikipedia: S-400 missile system",
      "CSIS Missile Threat Database",
      "IISS Military Balance"
    ],
    "notes": "Mobile phased-array SAM system deployed by Russia and allies. Operator can engage up to 36 targets simultaneously across 160-degree sector. Four primary missile variants (48N6, 55R"
  },
  {
    "id": "samp-t",
    "name": "SAMP/T",
    "category": "sam",
    "country": "France / Italy (Eurosam Joint Venture)",
    "role": "Mobile long-range air and ballistic missile defense",
    "specs": {
      "range_km": 120,
      "speed_kph": 5560,
      "ceiling_m": 20000,
      "payload_kg": 43,
      "pk_est": 0.8,
      "cost_usd": 500000000
    },
    "sources": [
      "https://en.wikipedia.org/wiki/SAMP/T",
      "https://missilethreat.csis.org/defsys/samp-t/",
      "https://www.thalesgroup.com/en/solutions-catalogue/defence/air/samp/t-ng-air-defence-system"
    ],
    "notes": "Original SAMP/T system (MAMBA variant). Fires Aster 30 missiles: range 120 km vs air-breathing targets; 20 km service ceiling; Mach 4.5 speed; warhead ~43 kg (focused fragmentation"
  },
  {
    "id": "thaad",
    "name": "THAAD",
    "category": "sam",
    "country": "United States",
    "role": "Terminal-phase ballistic missile defense system",
    "specs": {
      "range_km": 200,
      "speed_kph": 10000,
      "ceiling_m": 150000,
      "payload_kg": 1044,
      "pk_est": 0.85,
      "cost_usd": 1000000000
    },
    "sources": [
      "Wikipedia - Terminal High Altitude Area Defense",
      "CSIS Missile Threat - THAAD",
      "Raytheon Technologies (RTX) - THAAD system specs"
    ],
    "notes": "Kinetic kill-to-hit interceptor (no explosive warhead). Single battery comprises 6 transporter erector launchers with 8 missiles each (48 total), one AN/TPY-2 radar, 3 control stat"
  },
  {
    "id": "rafale",
    "name": "Dassault Rafale",
    "category": "fighter",
    "country": "France",
    "role": "Multirole fighter; air superiority and omnirole combat",
    "specs": {
      "range_km": 1850,
      "speed_kph": 2222,
      "ceiling_m": 15835,
      "payload_kg": 9000,
      "pk_est": 0.78,
      "cost_usd": 115000000
    },
    "sources": [
      "Wikipedia: Dassault Rafale",
      "Dassault Aviation official specifications",
      "Global Military database (2026)"
    ],
    "notes": "4.5-generation twin-engine canard-delta fighter. Equipped with RBE2 AESA radar, IRST (OSF), MBDA Meteor BVR missiles, and MICA medium-range AAMs. Maximum takeoff weight 24,500 kg. "
  },
  {
    "id": "eurofighter",
    "name": "Eurofighter Typhoon",
    "category": "fighter",
    "country": "European (Multinational: Germany, Italy, Spain, UK)",
    "role": "Air superiority and multi-role fighter",
    "specs": {
      "range_km": 3790,
      "speed_kph": 2500,
      "ceiling_m": 17500,
      "payload_kg": 6500,
      "pk_est": 0.85,
      "cost_usd": 122000000
    },
    "sources": [
      "Wikipedia: Eurofighter Typhoon",
      "Eurofighter GmbH manufacturer brochures",
      "IISS Military Balance annual"
    ],
    "notes": "Mach 2.0+ supersonic fighter (4.5-generation); delta-canard configuration with relaxed static stability; twin Eurojet EJ200 turbofans. Combat radius ~1300 km with internal fuel + c"
  },
  {
    "id": "f-15e",
    "name": "F-15E Strike Eagle",
    "category": "fighter",
    "country": "United States",
    "role": "All-weather deep strike fighter with air-to-air capability",
    "specs": {
      "range_km": 4450,
      "speed_kph": 2696,
      "ceiling_m": 18288,
      "payload_kg": 10409,
      "cost_usd": 31100000
    },
    "sources": [
      "Wikipedia: McDonnell Douglas F-15E Strike Eagle",
      "Federation of American Scientists: F-15 Eagle",
      "Air & Space Forces Magazine: F-15E"
    ],
    "notes": "Flyaway cost $31.1M (FY1998 dollars, ~$62M in 2026 CPI). Maximum speed Mach 2.54 (1,676 mph) at altitude. Service ceiling 60,000 ft. Combat radius 1,271 km; maximum ferry range 4,4"
  },
  {
    "id": "f-16",
    "name": "F-16 Fighting Falcon",
    "category": "fighter",
    "country": "USA",
    "role": "Air superiority and strike fighter",
    "specs": {
      "range_km": 860,
      "speed_kph": 2124,
      "ceiling_m": 15240,
      "payload_kg": 7700,
      "pk_est": 0.85,
      "cost_usd": 200000000
    },
    "sources": [
      "Wikipedia (F-16 Fighting Falcon)",
      "USAF Fact Sheets",
      "Lockheed Martin Public Specifications"
    ],
    "notes": "Combat radius ~860 km with 2 AIM-120 missiles and internal fuel. Max speed Mach 2.0+ at altitude. Service ceiling 50,000 ft. Weapon load up to 7,700 kg. Unit cost ~$178-220 million"
  },
  {
    "id": "f-35a",
    "name": "F-35A Lightning II",
    "category": "fighter",
    "country": "United States",
    "role": "Multirole conventional takeoff fighter-bomber",
    "specs": {
      "range_km": 900,
      "speed_kph": 1920,
      "ceiling_m": 15240,
      "payload_kg": 8200,
      "pk_est": 0.85,
      "cost_usd": 82000000
    },
    "sources": [
      "Wikipedia F-35 Lightning II",
      "Lockheed Martin manufacturer brochures",
      "U.S. Department of Defense budget estimates (FY2023)"
    ],
    "notes": "Combat radius ~900 km (typical loaded mission); max speed Mach 1.6+ (~1,920 kph at sea level); service ceiling 50,000 feet; internal bay payload ~8,200 kg; unit recurring flyaway c"
  },
  {
    "id": "mig-29",
    "name": "MiG-29",
    "category": "fighter",
    "country": "Soviet Union / Russia",
    "role": "Air-to-air and multi-role combat fighter",
    "specs": {
      "range_km": 1430,
      "speed_kph": 2190,
      "ceiling_m": 17500,
      "payload_kg": 3160,
      "pk_est": 0.85,
      "cost_usd": 29000000
    },
    "sources": [
      "Wikipedia: Mikoyan MiG-29",
      "IISS Military Balance",
      "CSIS Missile Threat"
    ],
    "notes": "Twin-engine fighter introduced 1982; Mach 2.3+ speed; widely exported to ~30 air forces. Cost ~$29M flyaway (1990s era, variants $15M–$50M+). Primary armament: two R-27 (~1.4 km ra"
  },
  {
    "id": "su-34",
    "name": "Su-34",
    "category": "fighter",
    "country": "Russia",
    "role": "All-weather supersonic medium-range strike fighter-bomber with standoff cruise missile cap",
    "specs": {
      "range_km": 4250,
      "speed_kph": 2200,
      "ceiling_m": 15000,
      "payload_kg": 8000,
      "pk_est": 0.25,
      "cost_usd": 36000000
    },
    "sources": [
      "Wikipedia: Sukhoi Su-34",
      "Airforce Technology Su-34 Fullback",
      "Global Military Review Su-34 Specifications"
    ],
    "notes": "First flight 1990; operational service began March 2014. Ferry range 4,250 km; combat radius 1,100 km. Maximum speed Mach 1.8 at altitude, Mach 1.2 at low level. Twin AL-31FM1 turb"
  },
  {
    "id": "su-35",
    "name": "Su-35",
    "category": "fighter",
    "country": "Russia",
    "role": "Single-seat air superiority fighter with multi-role capability",
    "specs": {
      "range_km": 1600,
      "speed_kph": 2400,
      "ceiling_m": 18000,
      "payload_kg": 8000,
      "pk_est": 0.75,
      "cost_usd": 65000000
    },
    "sources": [
      "Wikipedia: Sukhoi Su-35",
      "Jane's All The World's Aircraft 2013",
      "Russian Defense Ministry MAKS Air Show 2009 procurement announcement"
    ],
    "notes": "4.5-generation fighter with thrust-vectoring AL-41F1S engines, N035 Irbis-E PESA radar (400 km detection range), supermaneuverability capability (+9g), canard-free design. Combat r"
  },
  {
    "id": "bmp-3",
    "name": "BMP-3",
    "category": "armor",
    "country": "Russia / Soviet Union",
    "role": "Infantry fighting vehicle with 100mm gun and dual-axis stabilization",
    "specs": {
      "range_km": 600,
      "speed_kph": 72,
      "pk_est": 0.65,
      "cost_usd": 3500000
    },
    "sources": [
      "https://en.wikipedia.org/wiki/BMP-3",
      "https://www.army-technology.com/projects/bmp-3/",
      "https://www.globalsecurity.org/military/world/russia/bmp-3-edz.htm"
    ],
    "notes": "Primary armament: 100mm 2A70 smoothbore cannon (coax 30mm 2A72 autocannon, AGS-30 grenade launcher). Engine: UTD-29M diesel 500 hp. Hull/turret aluminum alloy with steel reinforcem"
  },
  {
    "id": "challenger-2",
    "name": "Challenger 2",
    "category": "armor",
    "country": "United Kingdom",
    "role": "Main battle tank",
    "specs": {
      "range_km": 500,
      "speed_kph": 56,
      "payload_kg": 120,
      "pk_est": 0.75,
      "cost_usd": 4500000
    },
    "sources": [
      "Wikipedia - Challenger 2",
      "IISS Military Balance",
      "UK Ministry of Defence specifications"
    ],
    "notes": "British primary MBT, Rolls-Royce/Vickers design introduced 1994. Cold War-era hull refined through 1990s–2000s with composite armor, stabilized 120mm rifled gun, and integrated fir"
  },
  {
    "id": "leopard-2",
    "name": "Leopard 2A6",
    "category": "armor",
    "country": "Germany",
    "role": "Main battle tank with 120mm L/55 smoothbore gun",
    "specs": {
      "range_km": 500,
      "speed_kph": 72,
      "payload_kg": 24,
      "pk_est": 0.8,
      "cost_usd": 7750000
    },
    "sources": [
      "Wikipedia (Leopard 2)",
      "IISS Military Balance",
      "Krauss-Maffei Wegmann manufacturer specifications"
    ],
    "notes": "Leopard 2A6 upgrade introduced Rheinmetall 120mm L/55 smoothbore gun (vs earlier L/44), improved fire control, and composite armor package. Engine: MTU MB 873 diesel (1,479 hp). Sp"
  },
  {
    "id": "m1-abrams",
    "name": "M1A2 Abrams",
    "category": "armor",
    "country": "United States",
    "role": "Main battle tank",
    "specs": {
      "range_km": 4,
      "speed_kph": 72,
      "payload_kg": 40,
      "pk_est": 0.85,
      "cost_usd": 6000000
    },
    "sources": [
      "Wikipedia: M1 Abrams",
      "U.S. Army Fact Sheet",
      "General Dynamics Land Systems"
    ],
    "notes": "M1A2 carries 120mm M256 smoothbore main gun with typical anti-armor range ~4 km; road speed 72 km/h; crew of 4; composite armor; unit cost publicly cited as $4–9M depending on vari"
  },
  {
    "id": "bradley",
    "name": "M2 Bradley",
    "category": "armor",
    "country": "United States",
    "role": "Infantry fighting vehicle with TOW anti-tank capability",
    "specs": {
      "range_km": 480,
      "speed_kph": 66,
      "payload_kg": 12.4,
      "pk_est": 0.72,
      "cost_usd": 3200000
    },
    "sources": [
      "https://en.wikipedia.org/wiki/M2_Bradley",
      "https://www.globalsecurity.org/military/systems/ground/m2.htm",
      "https://www.army-technology.com/projects/bradley-m2-m3/"
    ],
    "notes": "M2 Bradley entered service 1981, crewed by 3 (commander, gunner, driver) + 6 infantry. Armed with M242 25mm Bushmaster cannon (200 rpm, 2000m range) and coaxial M240C 7.62mm machin"
  },
  {
    "id": "t-72b3",
    "name": "T-72B3",
    "category": "armor",
    "country": "Russia",
    "role": "Main battle tank",
    "specs": {
      "range_km": 500,
      "speed_kph": 65,
      "ceiling_m": 0,
      "payload_kg": 45,
      "pk_est": 0.62,
      "cost_usd": 1500000
    },
    "sources": [
      "https://en.wikipedia.org/wiki/2A46_125_mm_gun",
      "https://www.globalsecurity.org/military/world/russia/t-72b3.htm",
      "https://www.army-technology.com/projects/t-72b3m-main-battle-tank/"
    ],
    "notes": "T-72B3 (introduced 2010) is a deep modernization of existing T-72B tanks, not new production. Armed with 125mm 2A46M-5 smoothbore gun carrying 41 rounds (20x APFSDS, 10x HEAT, 9x H"
  },
  {
    "id": "t-90m",
    "name": "T-90M",
    "category": "armor",
    "country": "Russia",
    "role": "Main battle tank with composite armor and modern fire control",
    "specs": {
      "range_km": 550,
      "speed_kph": 70,
      "payload_kg": 3000,
      "pk_est": 0.65,
      "cost_usd": 4500000
    },
    "sources": [
      "https://en.wikipedia.org/wiki/T-90",
      "https://www.armyrecognition.com/military-products/army/main-battle-tanks/main-battle-tanks/t-90m-model-2017-mbt-main-battle-tank-technical-data-sheet",
      "https://www.militaryfactory.com/armor/detail.php?armor_id=161"
    ],
    "notes": "The T-90M (Proryv-3) is the most advanced variant of the T-90 MBT series. Equipped with a 1,130 hp V-92S2F diesel engine and 125mm 2A82-1M smoothbore gun with autoloader (10 rounds"
  },
  {
    "id": "javelin",
    "name": "FGM-148 Javelin",
    "category": "infantry",
    "country": "United States",
    "role": "Man-portable fire-and-forget anti-tank guided missile",
    "specs": {
      "range_km": 2.5,
      "speed_kph": 504,
      "ceiling_m": 150,
      "payload_kg": 8.4,
      "pk_est": 0.8,
      "cost_usd": 146100
    },
    "sources": [
      "Wikipedia - FGM-148 Javelin",
      "CSIS Missile Threat - FGM-148 Javelin",
      "Lockheed Martin Javelin weapon system"
    ],
    "notes": "Tandem-charge HEAT warhead with dual-mode engagement (top attack vs tanks at 150m altitude; direct attack vs structures/helicopters at 60m altitude). Soft-launch mechanism prevents"
  },
  {
    "id": "himars",
    "name": "M142 HIMARS",
    "category": "infantry",
    "country": "United States",
    "role": "Mobile multiple-launch rocket system for precision strike and artillery",
    "specs": {
      "range_km": 92,
      "speed_kph": 85,
      "ceiling_m": 0,
      "payload_kg": 90,
      "pk_est": 0.8,
      "cost_usd": 4900000
    },
    "sources": [
      "Wikipedia: M142 HIMARS",
      "Lockheed Martin HIMARS product page",
      "CSIS Missile Threat database"
    ],
    "notes": "Range varies by munition: M26 (15-32 km), M31 GMLRS (15-92 km), ATACMS (up to 300 km). Payload is single M31 warhead (90 kg); ATACMS carries 213-247 kg warhead. Cost reflects FY202"
  },
  {
    "id": "m777",
    "name": "M777 howitzer",
    "category": "infantry",
    "country": "United Kingdom / United States",
    "role": "Lightweight towed 155mm artillery gun",
    "specs": {
      "range_km": 30,
      "payload_kg": 43.2,
      "pk_est": 0.8,
      "cost_usd": 3000000
    },
    "sources": [
      "Wikipedia M777 howitzer",
      "BAE Systems Land and Armaments",
      "US Department of Defense procurement records"
    ],
    "notes": "Ultralightweight 155mm towed howitzer. Designed by Vickers Shipbuilding and Engineering (UK, 1987), manufactured by BAE Systems (US). In service since 2005. Crew: 8 personnel. Comb"
  },
  {
    "id": "nlaw",
    "name": "NLAW",
    "category": "infantry",
    "country": "Sweden / United Kingdom",
    "role": "Man-portable fire-and-forget anti-tank missile",
    "specs": {
      "range_km": 0.8,
      "payload_kg": 1.8,
      "pk_est": 0.8,
      "cost_usd": 35000
    },
    "sources": [
      "Wikipedia: NLAW",
      "Saab Bofors Dynamics (manufacturer)",
      "Thales Air Defence (final assembly)"
    ],
    "notes": "Fire-and-forget lightweight shoulder-fired system with predicted line-of-sight (PLOS) guidance. Warhead uses HEAT (High-Explosive Anti-Tank) with >500mm rolled steel penetration. D"
  },
  {
    "id": "tos-1a",
    "name": "TOS-1A Solntsepyok",
    "category": "infantry",
    "country": "Russia",
    "role": "Heavy thermobaric multi-launch weapon system",
    "specs": {
      "range_km": 6,
      "speed_kph": 60,
      "payload_kg": 2400,
      "pk_est": 0.65,
      "cost_usd": 2500000
    },
    "sources": [
      "Wikipedia: TOS-1A Solntsepyok",
      "IISS Military Balance",
      "Jane's Fighting Vehicles"
    ],
    "notes": "Thermobaric multi-tube rocket launcher mounted on tracked platform; 40-60 launch tubes; effective range typically 3–6 km depending on munition type and terrain. Pk_est 0.65 reflect"
  },
  {
    "id": "grigorovich",
    "name": "Admiral Grigorovich-class frigate",
    "category": "naval",
    "country": "Russia",
    "role": "Multi-purpose frigate with air defense and anti-ship capability",
    "specs": {
      "range_km": 4500,
      "speed_kph": 56,
      "ceiling_m": 0,
      "payload_kg": 0,
      "pk_est": 0.45,
      "cost_usd": 300000000
    },
    "sources": [
      "Wikipedia — Admiral Grigorovich-class frigate",
      "IISS Military Balance 2024",
      "Janes Fighting Ships"
    ],
    "notes": "Displacement: ~4,500 tonnes. Armament: Kalibr LACM (land-attack cruise missile), Grad MLRS, Pantsir-SM ADS (16x missiles), 100mm gun, 2x 14.5mm MG, 2x Paket-NK ASROC/torpedo tubes."
  },
  {
    "id": "arleigh-burke",
    "name": "Arleigh Burke-class destroyer",
    "category": "naval",
    "country": "United States",
    "role": "Multi-mission guided-missile destroyer",
    "specs": {
      "range_km": 1850,
      "speed_kph": 56,
      "ceiling_m": 0,
      "payload_kg": 0,
      "pk_est": 0.85,
      "cost_usd": 1840000000
    },
    "sources": [
      "Wikipedia: Arleigh Burke-class destroyer",
      "US Navy official specifications",
      "IISS Military Balance"
    ],
    "notes": "Modern guided-missile destroyer; displacement 9,200 tons; length 154 m. Armed with 96 VLS cells (Tomahawk 1000+ nm, SM-6 air defense, ESSM, VLA ASW), 127 mm gun, 2x Phalanx CIWS, 6"
  },
  {
    "id": "kilo-sub",
    "name": "Kilo-class submarine",
    "category": "naval",
    "country": "Russia (USSR/Soviet Union)",
    "role": "Diesel-electric attack submarine for coastal and regional warfare",
    "specs": {
      "range_km": 7500,
      "speed_kph": 37,
      "ceiling_m": 300,
      "payload_kg": 18000,
      "pk_est": 0.65,
      "cost_usd": 250000000
    },
    "sources": [
      "Wikipedia: Kilo-class submarine",
      "GlobalSecurity.org: Kilo Class - Project 877",
      "ArmyRecognition.com: Improved Kilo-Class Type 636"
    ],
    "notes": "The Kilo-class (NATO reporting name; Russian designation Project 877 Paltus and improved Project 636 Klub) is a Soviet-designed diesel-electric attack submarine first commissioned "
  },
  {
    "id": "type-055",
    "name": "Type 055 destroyer",
    "category": "naval",
    "country": "China",
    "role": "Multi-role guided-missile destroyer and fleet air-defense platform",
    "specs": {
      "range_km": 9300,
      "speed_kph": 56,
      "cost_usd": 888000000
    },
    "sources": [
      "https://en.wikipedia.org/wiki/Type_055_destroyer",
      "https://www.naval-technology.com/projects/type-055-class-destroyers/",
      "https://missilethreat.csis.org/china-launches-new-guided-missile-destroyers/"
    ],
    "notes": "Type 055 (Renhai-class) is China's largest modern destroyer, displacing 11,000 t (standard) and 12–13,000 t (full load). Dimensions: 180 m length × 20 m beam × 6.6 m draft. Crew: 3"
  }
];
